# Generated by Django 4.0.5 on 2023-04-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quran_app', '0003_quran_suras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quran_suras',
            old_name='name',
            new_name='sura_name',
        ),
    ]
